### ISSUE TITLE
Any reason to stick to Californium 1.1.0-SNAPSHOT instead of a 2.0-2.4 release?

### ISSUE THREAD

**Issue by boaks** [riccardo94p/CoAP-Proxy#1]
Just to improve the Californium development:

Have there been any serious reasons not to use one of the 2. releases of Californium?

**Comment by riccardo94p** [comment]
Hello, I don't think there are particular reasons. This is what we worked with at the University.

**Comment by boaks** [comment]
Thanks for your fast answer!

(Just for the case you want to try to migrate to 2.4.1, don't hesitate to open issues in Californium.)
